### ISSUE TITLE
Error while Converting

### ISSUE THREAD

**Issue by fancythedeveloper** [qimiko/gdlevelconverter#6]
Trying this out, and uhh...

`deez nuts>gd-level-converter "Hard Sharp 2.gmd" -g all -o "Hard Sharp.gmd"
Loading level from file `Hard Sharp 2.gmd`
Traceback (most recent call last):
  File "c:\users\fancy\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fancy\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Fancy\AppData\Local\Programs\Python\Python39\Scripts\gd-level-converter.exe\__main__.py", line 7, in <module>
  File "c:\users\fancy\appdata\local\programs\python\python39\lib\site-packages\gdlevelconverter\command_line.py", line 134, in _main
    level = load_level_from_target(args.target)
  File "c:\users\fancy\appdata\local\programs\python\python39\lib\site-packages\gdlevelconverter\command_line.py", line 31, in load_level_from_target
    level = GJGameLevel.from_gmd(gmd_string)
  File "c:\users\fancy\appdata\local\programs\python\python39\lib\site-packages\gdlevelconverter\gjobjects\gjgamelevel.py", line 97, in from_gmd
    instance.two_player = int(element_dict.get("k43", 0))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

**Comment by qimiko** [comment]
can you send the gmd file, if you're able to? i'd like to try some things with it

**Comment by fancythedeveloper** [comment]
> can you send the gmd file, if you're able to? i'd like to try some things with it

Sure
[extractme.zip](https://github.com/qimiko/gdlevelconverter/files/8839387/extractme.zip)

**Comment by fancythedeveloper** [comment]
Bumping in case you forgot about it.

**Comment by qimiko** [comment]
there you go, should be fixed now :+1: enjoy
